A Complete Guide to Using Progress Bars in Python<br>
https://towardsdatascience.com/a-complete-guide-to-using-progress-bars-in-python-aa7f4130cda8

In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

df = pd.DataFrame(np.random.randint(0, 1000, (100000, 600)))

tqdm.pandas(desc="my bar!")

df.progress_apply(lambda x: x**2)

my bar!: 100%|██████████| 600/600 [00:01<00:00, 338.98it/s]

,0,1,2,3,4,5,6,7,8,9,...,590,591,592,593,594,595,596,597,598,599
0,48400,1024,7056,512656,984064,305809,54289,900601,549081,15376,...,214369,962361,117649,22500,80656,765625,396900,159201,506944,962361
1,30625,900601,813604,50625,734449,10000,3025,299209,29929,49284,...,10000,912025,169744,529,674041,259081,4225,11881,82944,868624
2,931225,784,194481,868624,675684,269361,670761,904401,430336,328329,...,312481,6724,34969,550564,483025,261121,251001,485809,620944,624100
3,367236,765625,561001,608400,570025,781456,4,763876,25600,139129,...,138384,214369,790321,131044,429025,3364,912025,956484,982081,938961
4,440896,195364,42025,356409,9216,904401,588289,92416,171396,103684,...,703921,5776,961,381924,872356,708964,506944,760384,39204,799236
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,106929,399424,535824,55225,172225,547600,148996,24964,756900,142129,...,484416,846400,1,1024,519841,73984,396900,656100,42436,16129
99996,81225,942841,10816,535824,351649,91204,393129,74529,151321,407044,...,142884,736164,6400,152100,490000,770884,33124,76729,148225,413449
99997,184900,112896,249001,509796,446224,184041,808201,379456,783225,89401,...,576,4225,169,114921,167281,150544,173056,15129,550564,249001
99998,313600,185761,609961,426409,20736,44944,430336,164836,10404,27556,...,417316,33856,31684,220900,390625,346921,3136,23409,774400,777924
99999,184041,589824,180625,9025,927369,330625,404496,8836,123201,767376,...,68121,441,77284,26244,99225,458329,291600,358801,187489,145161